[package]
name = "forceatlas2"
version = "0.5.0"
description = "fast force-directed generic n-dimension graph layout"
authors = ["tuxmain <tuxmain@zettascript.org>"]
repository = "https://framagit.org/ZettaScript/forceatlas2-rs"
documentation = "https://docs.rs/forceatlas2"
keywords = ["graph", "force"]
categories = ["visualization"]
license = "AGPL-3.0-only"
edition = "2021"

[profile.release]
codegen-units = 1
debug = true

[dependencies]
itertools = "0.11.0"
maths-traits = "0.2.1"
nbody_barnes_hut = { version = "0.1.0", optional = true }
num-traits = "0.2.15"
rand = { version = "0.8.5", optional = true }
rayon = { version = "1.7.0", optional = true }

[dev-dependencies]
alloc_counter = "0.0.4"
plotters = "0.3.5"
scanrs = "0.3.0"
sdl2 = "0.35.2"
stl = { git = "https://github.com/etrombly/rust-stl" }

[features]
default = ["rand", "parallel"]
barnes_hut = ["nbody_barnes_hut"]
parallel = ["rayon"]

[workspace]
members = ["examples/viz"]
